final Map<String, String> languageMap = {
  'multi': 'Multilingual (Spanish + English)',
  'bg': 'Bulgarian',
  'ca': 'Catalan',
  'zh-CN': 'Chinese (Mainland China)',
  'zh-TW': 'Chinese (Taiwan)',
  'zh-HK': 'Chinese (Traditional, Hong Kong)',
  'cs': 'Czech',
  'da': 'Danish',
  'da-DK': 'Danish',
  'nl': 'Dutch',
  'en': 'English',
  'en-US': 'English (United States)',
  'en-AU': 'English (Australia)',
  'en-GB': 'English (United Kingdom)',
  'en-NZ': 'English (New Zealand)',
  'en-IN': 'English (India)',
  'et': 'Estonian',
  'fi': 'Finnish',
  'nl-BE': 'Flemish',
  'fr': 'French',
  'fr-CA': 'French (Canada)',
  'de': 'German',
  'de-CH': 'German (Switzerland)',
  'el': 'Greek',
  'hi': 'Hindi',
  'hu': 'Hungarian',
  'id': 'Indonesian',
  'it': 'Italian',
  'ja': 'Japanese',
  'ko-KR': 'Korean',
  'lv': 'Latvian',
  'lt': 'Lithuanian',
  'ms': 'Malay',
  'no': 'Norwegian',
  'pl': 'Polish',
  'pt': 'Portuguese',
  'pt-BR': 'Portuguese (Brazil)',
  'pt-PT': 'Portuguese (Portugal)',
  'ro': 'Romanian',
  'ru': 'Russian',
  'sk': 'Slovak',
  'es': 'Spanish',
  'es-419': 'Spanish (Latin America & Caribbean)',
  'sv-SE': 'Swedish (Sweden)',
  'th-TH': 'Thai (Thailand)',
  'tr': 'Turkish',
  'uk': 'Ukrainian',
  'vi': 'Vietnamese',
};