final Map<String, String> languageMap = {
  "bg-BG": "Bulgarian (Bulgaria)",
  "ca-ES": "Catalan",
  "zh-CN": "Chinese (Mandarin, Simplified)",
  "zh-TW": "Chinese (Taiwanese Mandarin, Traditional)",
  "zh-HK": "Chinese (Cantonese, Traditional)",
  "cs-CZ": "Czech (Czechia)",
  "da-DK": "Danish (Denmark)",
  "nl-NL": "Dutch (Netherlands)",
  "en-US": "English (United States)",
  "en-AU": "English (Australia)",
  "en-GB": "English (United Kingdom)",
  "en-NZ": "English (New Zealand)",
  "en-IN": "English (India)",
  "et-EE": "Estonian (Estonia)",
  "fi-FI": "Finnish (Finland)",
  "nl-BE": "Dutch (Belgium)",
  "fr-FR": "French (France)",
  "fr-CA": "French (Canada)",
  "de-DE": "German (Germany)",
  "de-CH": "German (Switzerland)",
  "el-GR": "Greek (Greece)",
  "hi-IN": "Hindi (India)",
  "hu-HU": "Hungarian (Hungary)",
  "id-ID": "Indonesian (Indonesia)",
  "it-IT": "Italian (Italy)",
  "ja-JP": "Japanese (Japan)",
  "ko-KR": "Korean (Korea)",
  "lv-LV": "Latvian (Latvia)",
  "lt-LT": "Lithuanian (Lithuania)",
  "ms-MY": "Malay (Malaysia)",
  "nb-NO": "Norwegian Bokmål (Norway)",
  "pl-PL": "Polish (Poland)",
  "pt-BR": "Portuguese (Brazil)",
  "pt-PT": "Portuguese (Portugal)",
  "ro-RO": "Romanian (Romania)",
  "ru-RU": "Russian (Russia)",
  "sk-SK": "Slovak (Slovakia)",
  "es-ES": "Spanish (Spain)",
  "sv-SE": "Swedish (Sweden)",
  "th-TH": "Thai (Thailand)",
  "tr-TR": "Turkish (Türkiye)",
  "uk-UA": "Ukrainian (Ukraine)",
  "vi-VN": "Vietnamese (Vietnam)",
};